openapi: 3.0.1
info:
  title: TODO Plugin
  description: TODO.
  version: "v1"
servers:
  - url: http://localhost:5003
paths:
  /handle-prompt:
    post:
      operationId: handlePrompt
      summary: Handle a user prompt
      parameters:
        - in: prompt
          name: prompt
          schema:
            type: string
          required: true
          description: TODO
      requestBody:
        required: true
        content: text/plain
      responses:
        "200":
          description: OK

components:
  schemas:
    addTodoRequest:
      type: object
      required:
        - todo
      properties:
        todo:
          type: string
          description: The todo to add to the list.
          required: true
