#!/usr/bin/env bash

set -euo pipefail

prepare () {
  sudo mkdir -p $1

  # sudo chown -R dark:dark $1
  # note: we updated from the above to the below because of some symlinked
  #   binaries that could exist in cached dirs

  sudo find "$1" ! -type l -exec chown dark:dark {} +
}

prepare "backend/Build"
prepare "/home/dark/.nuget"
