version: 2
id: 11111111-1111-1111-1111-111111111111
main: main
client:
  - client/prelude.dark
  - client/html.dark
  - client/openai.dark
  - client/model.dark
  - client/update.dark
  - client/view.dark
  - client/main.dark
  
